<a href="https://colab.research.google.com/github/ryzhokhina/Tensorflow-Dev-Exam-Preparation/blob/main/00_tensorflow_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
print(tf.__version__)

2.12.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,11,12,23])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 11, 12, 23], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[9,4],[9,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 4],
       [9, 7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
float_matrix = tf.constant([[1,2],[3,4],[5,6]], dtype = tf.float16)

In [ ]:
float_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [ ]:
float_matrix.ndim

2

In [ ]:
v_tensor = tf.Variable([10,7])

In [ ]:
v_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
v_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
v_tensor[0] = 6

TypeError: ignored

In [ ]:
v_tensor[0].assign(8)

In [ ]:
v_tensor

In [ ]:
vector[0]

In [ ]:
vector[0] = 9

In [ ]:
vector[0].assign = 9

In [ ]:
vector

In [ ]:
vector[0]

In [ ]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.uniform(shape = (3,3))

In [ ]:
random1

In [ ]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.uniform(shape = (3,3))

In [ ]:
random2

In [ ]:
random1 == random2

In [ ]:
random3 = tf.random.shuffle(random1)

In [ ]:
random3, random1

In [ ]:
random4 = tf.random.shuffle(random1, seed = 42)
random4

In [ ]:
random4

In [ ]:
print(tf.random.uniform([1]))  
print(tf.random.uniform([1]))

In [ ]:
print(tf.random.uniform([1])) 
print(tf.random.uniform([1]))

In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A

In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A

In [ ]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  
print(g()) 

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

In [ ]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

In [ ]:
print(foo())

In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

In [ ]:
unshuffled_tensor = tf.random.normal((4,2))

In [ ]:
unshuffled_tensor

In [ ]:
tf.random.set_seed(42)
sh_tensor = tf.random.shuffle(unshuffled_tensor, seed = 4)
sh_tensor


In [ ]:
tf.ones([3,4])

In [ ]:
tf.zeros(shape = (4,2))

In [ ]:
tf.zeros([3,2,4])

In [ ]:
import numpy as np

In [ ]:
np_A = np.ones((2,3))

In [ ]:
np_A

In [ ]:
np_A = np.arange(1,25, dtype = np.int32)
np_A

In [ ]:
A = tf.constant(np_A)
B = tf.constant(np_A, shape = (3,8))

In [ ]:
A

In [ ]:
B

In [ ]:
A.ndim, B.ndim

In [ ]:
tensor_4_dim = tf.zeros(shape = [2,3,4,5])

In [ ]:
tensor_4_dim

In [ ]:
tensor_4_dim.shape, tensor_4_dim.ndim, tf.size(tensor_4_dim)

In [ ]:
tensor_4_dim[0]

In [ ]:
tensor_4_dim[:2,:2,:2,:2]

In [ ]:
tensor_4_dim[:1,:1,:1]

In [ ]:
tensor_4_dim[1,1,1]

In [ ]:
rank_2_tensor = tf.constant([[10,7],[4,3]])

In [ ]:
rank_2_tensor

In [ ]:
rank_2_tensor[:,:1]

In [ ]:
rank_2_tensor[:,-1]

In [ ]:
rank_2_tensor[:,-1:]

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

In [ ]:
rank_3_tensor

In [ ]:
rank_3_tensor2 = tf.expand_dims(rank_2_tensor, 1)
rank_3_tensor2

In [ ]:
tf.expand_dims(rank_2_tensor, -1)

In [ ]:
tensor = rank_2_tensor
tensor

In [ ]:
tensor+10

In [ ]:
tensor-4

In [ ]:
tensor*2

In [ ]:
tensor/10

In [ ]:
tf.add(tensor,10)

In [ ]:
tf.math.multiply(tensor,2)

In [ ]:
tf.math.divide(tensor,10)

In [ ]:
tf.math.subtract(tensor,1)

In [ ]:
tensor = tf.constant([[10,7],[4,3]])

In [ ]:
tensor

In [ ]:
t2= tf.matmul(tensor, tensor)
t2

In [ ]:
tensor@tensor

In [ ]:
tensor*tensor

In [ ]:
t1 = tf.constant([[1,2],[3,4],[5,6]])

In [ ]:
t2 = tf.constant([[7,8],[9,10],[11,12]])

In [ ]:
t1, t2

In [ ]:
tf.reshape(t2, [2,3])

In [ ]:
t1@tf.reshape(t2, [2,3])

In [ ]:
tf.matmul(t1, tf.reshape(t2,[2,3]))

In [ ]:
tf.transpose(t1)

In [ ]:
tf.reshape(t1, [2,3])

In [ ]:
t1

In [ ]:
tf.tensordot(t1,t2,axes=0)

In [ ]:
tf.tensordot(tf.transpose(t1),t2,axes=1)

In [ ]:
tf.transpose(t1),t2

In [ ]:
t = tf.constant([[7,8],[9,10],[11,12]])

In [ ]:
t.dtype

In [ ]:
b = tf.constant([[7.0,8],[9,10],[11,12]])

In [ ]:
b.dtype

In [ ]:
b = tf.cast(b, dtype = tf.float16)
b

In [ ]:
b = tf.constant([[-7.0,-8],[-9,-10],[-11,-12]])

In [ ]:
b_abs = tf.abs(b)
b_abs

In [ ]:
b_min = tf.reduce_min(b)
b_min

In [ ]:
tf.minimum(b, b_abs)

In [ ]:
tf.minimum(b, b_min)

In [ ]:
tf.minimum(b, -18)

In [ ]:
b_max = tf.reduce_max(b)
b_max

In [ ]:
tf.maximum(b, b_abs)

In [ ]:
tf.maximum(b, 0)

In [ ]:
tf.reduce_sum(b)

In [ ]:
tf.reduce_sum(b, axis = 1)

In [ ]:
b

In [ ]:
tf.reduce_sum(b, axis = 0)

In [ ]:
tf.reduce_mean(b)

In [ ]:
tf.reduce_mean(b, axis = 0)

In [ ]:
tf.reduce_mean(b, axis = 1)

In [ ]:
import numpy as np

In [ ]:
E = tf.constant(np.random.randint(0,100, size = 50))

In [ ]:
tf.reduce_min(E)

In [ ]:
tf.reduce_max(E)

In [ ]:
tf.reduce_mean(E)

In [ ]:
tf.reduce_sum(E)

In [ ]:
E.ndim, tf.size(E), E.dtype, E.shape

In [ ]:
#variance of E

In [ ]:
E-tf.reduce_mean(E)

In [ ]:
(E-tf.reduce_mean(E))**2

In [ ]:
tf.reduce_sum((E-tf.reduce_mean(E))**2)

In [ ]:
var = tf.reduce_sum((E-tf.reduce_mean(E))**2)/tf.cast(tf.size(E), dtype=(tf.int64))

In [ ]:
var

In [ ]:
E.numpy().var()

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

In [ ]:
## standart deviation

In [ ]:
std = (tf.reduce_sum((E-tf.reduce_mean(E))**2)/tf.cast(tf.size(E), dtype=(tf.int64)))**0.5

In [ ]:
std

In [ ]:
E.numpy().std()

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype = tf.float16))

In [ ]:
tf.random.set_seed(42)
E = tf.random.uniform([50])
E

In [ ]:
tf.argmax(E)

In [ ]:
tf.argmin(E)

In [ ]:
E[42], E[16]

In [ ]:
tf.reduce_max(E), tf.reduce_min(E)

In [ ]:
tf.random.set_seed(42)
M = tf.random.uniform([5,5])
M

In [ ]:
tf.argmax(M)

In [ ]:
tf.argmax(M, axis = 1)

In [ ]:
tf.argmax(M)

In [ ]:
tf.random.set_seed(42)
E = tf.random.uniform(shape = (1,1,1,1,50))
E

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
E.shape, E.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
E_squeezed = tf.squeeze(E)
E_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

## One-hot encoding

In [ ]:
test_list = [0,2,3,4, 1, 3]
test_list

[0, 2, 3, 4, 1, 3]

In [ ]:
tf.one_hot(test_list, depth =5, axis = -1)

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(test_list, depth =5, axis = 0)

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(test_list, depth =5, axis = 1)

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [ ]:
J = tf.constant(np.array([3.0, 7, 10]))

In [ ]:
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J)

array([ 3.,  7., 10.])

In [ ]:
J.numpy()

array([ 3.,  7., 10.])

In [ ]:
numpy_J= tf.constant(np.array([1.0,2]))
tensor_J = tf.constant([1.0, 2])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
import tensorflow as tf

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!invidia-smi

/bin/bash: invidia-smi: command not found


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
#Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
vector = tf.constant([1,2,3])
scalar = tf.constant([1])
matrix = tf.constant([[1,2],[3,4]])
tensor = tf.constant(np.arange(50), shape = [2,5,5])


In [ ]:
#Find the shape, rank and size of the tensors you created in 1.
print("vector {},{},{}".format(vector.shape, vector.ndim, tf.size(vector)))
print("scalar {},{},{}".format(scalar.shape, scalar.ndim, tf.size(scalar)))
print("matrix {},{},{}".format(matrix.shape, matrix.ndim, tf.size(matrix)))
print("tensor {},{},{}".format(tensor.shape, tensor.ndim, tf.size(tensor)))


vector (3,),1,3
scalar (1,),1,1
matrix (2, 2),2,4
tensor (2, 5, 5),3,50


In [ ]:
#Create two tensors containing random values between 0 and 1 with shape [5, 300].
t1 = tf.random.uniform(shape = [5,300], minval =0, maxval = 1)
t2 = tf.random.uniform(shape = [5,300], minval = 0, maxval = 1)
t1, t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.03410864, 0.6712892 , 0.9341308 , ..., 0.12094486, 0.44511437,
         0.7034954 ],
        [0.688988  , 0.89092994, 0.4203391 , ..., 0.89263284, 0.13894904,
         0.05739295],
        [0.52934337, 0.7926327 , 0.534721  , ..., 0.73519635, 0.06316221,
         0.23610985],
        [0.6636108 , 0.98635423, 0.9437398 , ..., 0.9595028 , 0.3453461 ,
         0.45652127],
        [0.24432766, 0.14741111, 0.5308615 , ..., 0.18024969, 0.80593383,
         0.34907556]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.3484305 , 0.95428765, 0.56107426, ..., 0.11278844, 0.6615336 ,
         0.68999255],
        [0.71009946, 0.82667303, 0.19556022, ..., 0.28393877, 0.90871596,
         0.30467892],
        [0.875653  , 0.5618967 , 0.9336641 , ..., 0.95648944, 0.5939126 ,
         0.38912082],
        [0.38538778, 0.7584404 , 0.11576414, ..., 0.35072267, 0.81134164,
         0.16922927],
        [0.84335

In [ ]:
#Multiply the two tensors you created in 3 using matrix multiplication.

mult_t1_t2 = tf.matmul(t1, tf.transpose(t2))
mult_t1_t2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.44744 , 79.06798 , 73.171364, 72.90617 , 71.1685  ],
       [73.567085, 78.51357 , 73.47629 , 73.19177 , 71.37075 ],
       [70.249565, 76.99632 , 70.21444 , 70.96486 , 67.99918 ],
       [72.44569 , 76.5076  , 73.89001 , 71.2482  , 68.845055],
       [73.43387 , 78.06104 , 71.645164, 73.71147 , 68.8915  ]],
      dtype=float32)>

In [ ]:
#Multiply the two tensors you created in 3 using dot product.
dot_t1_t2 = tf.tensordot(t1, tf.transpose(t2), axes = 1)
dot_t1_t2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.44744 , 79.06798 , 73.171364, 72.90617 , 71.1685  ],
       [73.567085, 78.51357 , 73.47629 , 73.19177 , 71.37075 ],
       [70.249565, 76.99632 , 70.21444 , 70.96486 , 67.99918 ],
       [72.44569 , 76.5076  , 73.89001 , 71.2482  , 68.845055],
       [73.43387 , 78.06104 , 71.645164, 73.71147 , 68.8915  ]],
      dtype=float32)>

In [ ]:
#Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
t3 = tf.random.uniform(shape = [224, 224, 3], minval= 0, maxval = 1)
t3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5315008 , 0.7399769 , 0.09661651],
        [0.33271587, 0.27172506, 0.6901357 ],
        [0.35539234, 0.14974833, 0.16095972],
        ...,
        [0.7479389 , 0.53253686, 0.49402952],
        [0.3787638 , 0.4215008 , 0.7862258 ],
        [0.5761702 , 0.10568404, 0.871948  ]],

       [[0.30342972, 0.00435126, 0.28345442],
        [0.73012686, 0.19012749, 0.48619926],
        [0.06656551, 0.5134121 , 0.08196127],
        ...,
        [0.6518084 , 0.38060415, 0.91039336],
        [0.71098685, 0.7660469 , 0.01406765],
        [0.19650793, 0.7490692 , 0.48240006]],

       [[0.16516817, 0.94852316, 0.8174052 ],
        [0.34893048, 0.29878867, 0.8704263 ],
        [0.5145253 , 0.26821387, 0.19131982],
        ...,
        [0.7209611 , 0.22828794, 0.47804332],
        [0.03313828, 0.04320407, 0.55945003],
        [0.34764373, 0.82928765, 0.50761616]],

       ...,

       [[0.7849082 , 0.76302063, 0.05084443],
        [0.25

In [ ]:
#Find the min and max values of the tensor you created in 6 along the first axis.
min_val = tf.reduce_min(t3, axis = 0)
max_val = tf.reduce_max(t3, axis = 0)
min_val, max_val

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[5.77950478e-03, 4.35125828e-03, 2.53748894e-03],
        [1.79493427e-03, 2.55072117e-03, 3.22008133e-03],
        [1.72054768e-03, 6.65342808e-03, 1.10507011e-04],
        [5.87582588e-04, 5.02943993e-04, 3.59404087e-03],
        [2.83610821e-03, 5.57279587e-03, 3.79204750e-03],
        [1.56818628e-02, 1.01923943e-03, 6.78253174e-03],
        [5.89609146e-04, 3.78119946e-03, 8.56876373e-04],
        [6.39617443e-03, 5.09500504e-04, 1.39737129e-03],
        [2.19643116e-03, 2.00343132e-03, 1.55127048e-03],
        [2.08377838e-03, 5.84626198e-03, 1.34706497e-03],
        [8.88586044e-04, 1.78990364e-02, 4.76050377e-03],
        [9.60469246e-03, 3.77476215e-03, 6.51788712e-03],
        [1.64151192e-04, 2.72512436e-04, 2.76052952e-03],
        [1.57487392e-03, 5.91242313e-03, 2.76565552e-04],
        [8.96036625e-03, 1.02747679e-02, 5.04875183e-03],
        [9.28997993e-04, 9.04440880e-04, 2.89893150e-03],
        [5.57768345e-

In [ ]:
#Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
random_tensor = tf.constant(np.random.randint(10, 20, size = 224*224*3), shape = [1,224,224,3])
random_tensor.shape

TensorShape([1, 224, 224, 3])

In [ ]:
squeezed_t = tf.squeeze(random_tensor)
squeezed_t.shape

TensorShape([224, 224, 3])

In [ ]:
#Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
t10 = tf.constant(np.arange(30, 40))
t10

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])>

In [ ]:
tf.random.set_seed(42)
t10 = tf.random.shuffle(t10)
t10

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([35, 34, 39, 33, 36, 38, 32, 31, 37, 30])>

In [ ]:
index_max = tf.argmax(t10)
index_max

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
t10[index_max], tf.reduce_max(t10)

(<tf.Tensor: shape=(), dtype=int64, numpy=39>,
 <tf.Tensor: shape=(), dtype=int64, numpy=39>)

In [ ]:
#One-hot encode the tensor you created in 9.
tf.one_hot(t10, depth= 40)

<tf.Tensor: shape=(10, 40), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0